#!/usr/bin/env bash
# This script displays the username, user id, and home directory from the /etc/passwd file.
while IFS=: read -r username _ userid _ _ home _; do
echo "$username:$userid:$home"
done < /etc/passwd
