#!/usr/bin/env bash
# This script displays a story about each user in the /etc/passwd file.
while IFS=: read -r username _ userid group_id _ home shell; do
	echo "The user $username is part of the $group_id gang, lives in $home and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $username"
done < /etc/passwd
