#!/usr/bin/env bash
# This script parses the Apache access log file and displays the visitor IP and HTTP status code.
cat apache-access.log | tr -s ' ' '\n' | grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b' | sort | uniq -c | sort -nr | awk '{print $2, $4}' | head -n 10
