#!/usr/bin/env bash
# This script parses the Apache access log, groups visitors by IP and HTTP status code,
awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr | awk '{printf "%-5s %-15s %-5s\n", $1, $2, $3}'
