#!/usr/bin/env bash
# This script parses the Apache access log, groups visitors by IP and HTTP status code,
awk '{print $1, $9}' /var/log/apache2/access.log | sort | uniq -c | sort -nr | awk '{print $1, $2, $3}'
