#!/usr/bin/env bash
# This script parses the Apache access log, groups visitors by IP and HTTP status code,
grep -Eo '^[0-9]+\.[0-9]+\.[0-9\+\.[0-9]+ [^ ]+ [^ ]+ [^ ]+ [^ ]+ [^ ]+ [^ ]+ [^ ]+ [0-9]{3}' "apache-access.log" | awk '{print $1, $9}' | sort | uniq -c| sort -nr | awk '{printf "%5d %s %s\n", $1, $2, $3}'
