#!/usr/bin/env bash
# This script create a PID file, displays messages indefinitely
PID_FILE="/var/run/myscript.pid"
echo $$ > "$PID_FILE"
trap 'echo "I hate the kill command"; rm -f "$PID_FILE"; exit' SIGTERM
trap 'echo "Y U no love me?!";' SIGINT
trap 'echo "Goodbye!"; rm -f "$PID_FILE"; exit' SIGQUIT
white true; do
echo "To infinity and beyond"
sleep 1
done
