#!/usr/bin/env bash
# This script create a PID file, displays messages indefinitely
PID_FILE="/var/run/myscript.pid"
echo $$ > "$PID_FILE"
cleanup() {
    rm -f "$PID_FILE"
    echo "PID file deleted."
    exit 0
}
trap 'echo "I hate the kill command"; cleanup' SIGTERM
trap cleanup SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT
while true; do
    echo "To infinity and beyond"
    sleep 2
    done
