#!/usr/bin/env bash
# This script create a PID file, displays messages indefinitely
echo $$ > /var/run/myscript.pid

trap 'echo "I hate the kill command"; cleanup_and_exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid && exit' SIGQUIT SIGTERM

white true; do
echo "To infinity and beyond"
sleep 2
done
