#!/usr/bin/env bash
# THis script manages the manage_my_process
PID_FILE="/var/run/my_process.pid"
SCRIPT_PATH="./manage_my_process"

start() {
    $SCRIPT &
    echo "$!" > "$PID_FILE"
    echo "manage_my_process started"
}
stop() {
    if [ -f "$PID_FILE" ]; then
	pid=$(cat "$PID_FILE")
	kill "$pid"
	rm "$PID_FILE"
    fi
    echo "manage_my_process stopped"
}
case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	stop
	start
	echo "manage_my_process restarted"
	;;
    *)
	echo "Usage: manage_my_process {start|stop|restart}"
	exit 1
	;;
esac
exit 0
