#!/usr/bin/env bash
# This script lists the PID and process name of processes whose name contains 'bash'.
for pid in /proc/[0-9]*/; do
    pid_number=$(basename "$pid")
    process_name=$(cat "$pid/comm" 2>/dev/null)
    if [[ "$process_name" == *bash* ]]; then
	echo "$pid_number $process_name"
    fi
    done
