#!/usr/bin/env bash
# This script lists the PID and process name of processes whose name contains 'bash'.
for pid in /proc/[0-9]*; do
command= $(basename "$(readlink -f "$pid/exe" 2>/dev/null)" 2>/dev/null)
if [[ $command == *bash* ]]; then
echo "$(basename "$pid") $command"
fi
done