#!/usr/bin/env bash
# This script stops the '4-to_infinity_and_beyond'
pid=$(pgrep -f "4-to_infinity_and_beyond")
if [ -n "$pid" ]; then
kill "$pid"
echo "Process 4-to_infinity_and_beyond has been terminated."
else
echo "Process 4-to_infinity_and_beyond is not running."
fi