#!/usr/bin/env bash
# This script stops the '4-to_infinity_and_beyond' process without using kill or killall.
# Using 'pkill' to terminate the '4-to_infinity_and_beyond' process.
pkill -f "4-to_infinity_and_beyond"