#!/usr/bin/env bash
# This script forcefully kills the '7-highlander' process.
#Find the PID of the '7-highlander' process and kill it
pid=$(pgrep -f "7-highlander")
if [ -n "$pid" ]; then
    kill "$pid"
else
    echo "7-highlander process not found"
    fi
